const template = [
  {
    id: "habitacion1",
    name: "Habitacion Individual",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deleniti officia minus praesentium sapiente non dignissi",
    img: "./sources/habitacion1.jpg",
    price: 45,
    cantCamas: 1,
    cantBanos: 1,
    wifi: true,
    breakfast: false,
    airCondition: true,
    shower: true,
    tub: false,
    tv: false,
    health: false,
    disponible: 19,
  },
  {
    id: "habitacion2",
    name: "Habitacion Doble",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deleniti officia minus praesentium sapiente non dignissi",
    img: "./sources/habitacion2.jpg",
    price: 75,
    cantCamas: 2,
    cantBanos: 1,
    wifi: true,
    breakfast: false,
    airCondition: true,
    shower: true,
    tub: false,
    tv: false,
    health: false,
    disponible: 90,
  },
  {
    id: "habitacion3",
    name: "Habitacion Familiar",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deleniti officia minus praesentium sapiente non dignissi",
    img: "./sources/habitacion3.jpg",
    price: 95,
    cantCamas: 3,
    cantBanos: 2,
    wifi: true,
    breakfast: false,
    airCondition: true,
    shower: false,
    tub: false,
    tv: false,
    health: true,
    disponible: 10
  },
  {
    id: "habitacion4",
    name: "Habitacion Gold",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deleniti officia minus praesentium sapiente non dignissi",
    img: "./sources/habitacion4.jpg",
    price: 120,
    cantCamas: 2,
    cantBanos: 1,
    wifi: true,
    breakfast: true,
    airCondition: true,
    shower: false,
    tub: true,
    tv: false,
    health: true,
    disponible: 20,
  },
  {
    id: "habitacion5",
    name: "Habitacion Gold",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deleniti officia minus praesentium sapiente non dignissi",
    img: "./sources/habitacion5.jpg",
    price: 150,
    cantCamas: 2,
    cantBanos: 2,
    wifi: true,
    breakfast: true,
    airCondition: true,
    shower: true,
    tub: true,
    tv: true,
    health: true,
    disponible: 10,
  },
];
