const template = [
  {
    id: "habitacion1",
    name: "Habitacion Individual",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deleniti officia minus praesentium sapiente non dignissi",
    img: "./sources/habitacion1.jpg",
    price: 45,
    cantCamas: 1,
    cantPersonas: 1,
    icons: ["wifi", "air-conditioner", "shower", "tv"],
    incluido: [
      "Wifi",
      "Aire acondicionado",
      "Ducha agua helada/caliente",
      "Televisor",
    ],
    disponible: 19,
  },
  {
    id: "habitacion2",
    name: "Habitacion Doble",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deleniti officia minus praesentium sapiente non dignissi",
    img: "./sources/habitacion2.jpg",
    price: 75,
    cantCamas: 2,
    cantPersonas: 2,
    icons: ["wifi", "air-conditioner", "shower", "tv"],
    incluido: [
      "Wifi",
      "Aire acondicionado",
      "Ducha agua helada/caliente",
      "Televisor",
    ],
    disponible: 90,
  },
  {
    id: "habitacion3",
    name: "Habitacion Familiar",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deleniti officia minus praesentium sapiente non dignissi",
    img: "./sources/habitacion3.jpg",
    price: 95,
    cantCamas: 3,
    cantPersonas: 6,
    icons: ["wifi", "air-conditioner", "shower", "tv"],
    incluido: [
      "Wifi",
      "Aire acondicionado",
      "Ducha agua helada/caliente",
      "Televisor",
    ],
    disponible: 10,
  },
  {
    id: "habitacion4",
    name: "Habitacion Gold",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deleniti officia minus praesentium sapiente non dignissi",
    img: "./sources/habitacion4.jpg",
    price: 120,
    cantCamas: 2,
    cantPersonas: 2,
    icons: ["wifi", "air-conditioner", "utensils", "shower", "bath", "tv"],
    incluido: [
      "Wifi",
      "Aire acondicionado",
      "Desayuno",
      "Ducha agua caliente/helada",
      "Bañera",
      "Television",
    ],
    disponible: 20,
  },
  {
    id: "habitacion5",
    name: "Habitacion VIP",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum deleniti officia minus praesentium sapiente non dignissi",
    img: "./sources/habitacion5.jpg",
    price: 150,
    cantCamas: 2,
    cantPersonas: 2,
    icons: [
      "wifi",
      "air-conditioner",
      "utensils",
      "shower",
      "bath",
      "tv",
      "hot-tub",
    ],
    incluido: [
      "Wifi",
      "Aire acondicionado",
      "Desayuno",
      "Ducha agua helada/caliente",
      "Bañera",
      "Televisor",
      "Jacuzzi",
    ],
    disponible: 10,
  },
];
